export default {
    PLAY_QUEUE: "PLAY_QUEUE",
    TOGGLE_PLAYBACK: "TOGGLE_PLAYBACK",
    SKIP_FORWARD: "SKIP_FORWARD",
    SKIP_BACKWARD: "SKIP_BACKWARD",
    SEEK: "SEEK",
    PLAY_TRACK: "PLAY_TRACK",
    STOP_PLAYBACK: "STOP_PLAYBACK",
};
